version: '3'
services:
  postgres-charity:
    image: postgres:13.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qaz
      POSTGRES_DB: charity
    ports:
      - 8888:5432
    volumes:
      - ./postgres-charity:/postgres-charity