spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
        ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:8888/charity
    username: root
    password: qaz